give @s bright:gold_candle_stick
give @s bright:gold_white_candle_stick
give @s bright:gold_orange_candle_stick
give @s bright:gold_magenta_candle_stick
give @s bright:gold_light_blue_candle_stick
give @s bright:gold_yellow_candle_stick
give @s bright:gold_lime_candle_stick
give @s bright:gold_pink_candle_stick
give @s bright:gold_light_gray_candle_stick
give @s bright:gold_gray_candle_stick
give @s bright:gold_cyan_candle_stick
give @s bright:gold_purple_candle_stick
give @s bright:gold_blue_candle_stick
give @s bright:gold_brown_candle_stick
give @s bright:gold_green_candle_stick
give @s bright:gold_red_candle_stick
give @s bright:gold_black_candle_stick