give @s bright:white_light_bulb
give @s bright:orange_light_bulb
give @s bright:magenta_light_bulb
give @s bright:light_blue_light_bulb
give @s bright:yellow_light_bulb
give @s bright:lime_light_bulb
give @s bright:pink_light_bulb
give @s bright:light_gray_light_bulb
give @s bright:gray_light_bulb
give @s bright:cyan_light_bulb
give @s bright:purple_light_bulb
give @s bright:blue_light_bulb
give @s bright:brown_light_bulb
give @s bright:green_light_bulb
give @s bright:red_light_bulb
give @s bright:black_light_bulb