give @s bright:white_floor_light
give @s bright:orange_floor_light
give @s bright:magenta_floor_light
give @s bright:light_blue_floor_light
give @s bright:yellow_floor_light
give @s bright:lime_floor_light
give @s bright:pink_floor_light
give @s bright:light_gray_floor_light
give @s bright:gray_floor_light
give @s bright:cyan_floor_light
give @s bright:purple_floor_light
give @s bright:blue_floor_light
give @s bright:brown_floor_light
give @s bright:green_floor_light
give @s bright:red_floor_light
give @s bright:black_floor_light