give @s bright:netherite_candle_stick
give @s bright:netherite_white_candle_stick
give @s bright:netherite_orange_candle_stick
give @s bright:netherite_magenta_candle_stick
give @s bright:netherite_light_blue_candle_stick
give @s bright:netherite_yellow_candle_stick
give @s bright:netherite_lime_candle_stick
give @s bright:netherite_pink_candle_stick
give @s bright:netherite_light_gray_candle_stick
give @s bright:netherite_gray_candle_stick
give @s bright:netherite_cyan_candle_stick
give @s bright:netherite_purple_candle_stick
give @s bright:netherite_blue_candle_stick
give @s bright:netherite_brown_candle_stick
give @s bright:netherite_green_candle_stick
give @s bright:netherite_red_candle_stick
give @s bright:netherite_black_candle_stick