give @p const:black_brick_slab
give @p const:blue_brick_slab
give @p const:brown_brick_slab
give @p const:cyan_brick_slab
give @p const:gray_brick_slab
give @p const:green_brick_slab
give @p const:light_blue_brick_slab
give @p const:light_gray_brick_slab
give @p const:lime_brick_slab
give @p const:magenta_brick_slab
give @p const:orange_brick_slab
give @p const:pink_brick_slab
give @p const:purple_brick_slab
give @p const:red_brick_slab
give @p const:white_brick_slab
give @p const:yellow_brick_slab