give @p const:terracotta_shingle_slab
give @p const:black_terracotta_shingle_slab
give @p const:blue_terracotta_shingle_slab
give @p const:brown_terracotta_shingle_slab
give @p const:cyan_terracotta_shingle_slab
give @p const:gray_terracotta_shingle_slab
give @p const:green_terracotta_shingle_slab
give @p const:light_blue_terracotta_shingle_slab
give @p const:light_gray_terracotta_shingle_slab
give @p const:lime_terracotta_shingle_slab
give @p const:magenta_terracotta_shingle_slab
give @p const:orange_terracotta_shingle_slab
give @p const:pink_terracotta_shingle_slab
give @p const:purple_terracotta_shingle_slab
give @p const:red_terracotta_shingle_slab
give @p const:white_terracotta_shingle_slab
give @p const:yellow_terracotta_shingle_slab