give @s xmas:acacia_quarter_block_horz
give @s xmas:andesite_quarter_block_horz
give @s xmas:birch_quarter_block_horz
give @s xmas:blackstone_quarter_block_horz
give @s xmas:brick_quarter_block_horz
give @s xmas:cobbled_deepslate_quarter_block_horz
give @s xmas:cobblestone_quarter_block_horz
give @s xmas:crimson_quarter_block_horz
give @s xmas:cut_copper_quarter_block_horz
give @s xmas:cut_red_sandstone_quarter_block_horz
give @s xmas:cut_sandstone_quarter_block_horz
give @s xmas:dark_oak_quarter_block_horz
give @s xmas:dark_prismarine_quarter_block_horz
give @s xmas:deepslate_quarter_block_horz
give @s xmas:deepslate_tile_quarter_block_horz
give @s xmas:diorite_quarter_block_horz
give @s xmas:end_stone_quarter_block_horz
give @s xmas:exposed_cut_copper_quarter_block_horz
give @s xmas:granite_quarter_block_horz
give @s xmas:jungle_quarter_block_horz
give @s xmas:mossy_cobblestone_quarter_block_horz
give @s xmas:mossy_stone_brick_quarter_block_horz
give @s xmas:nether_brick_quarter_block_horz
give @s xmas:oak_quarter_block_horz
give @s xmas:oxidized_cut_copper_quarter_block_horz
give @s xmas:polished_andesite_quarter_block_horz
give @s xmas:polished_blackstone_brick_quarter_block_horz
give @s xmas:polished_blackstone_quarter_block_horz
give @s xmas:polished_deepslate_quarter_block_horz
give @s xmas:polished_diorite_quarter_block_horz
give @s xmas:polished_granite_quarter_block_horz
give @s xmas:prismarine_brick_quarter_block_horz
give @s xmas:prismarine_quarter_block_horz
give @s xmas:purpur_quarter_block_horz
give @s xmas:quartz_quarter_block_horz
give @s xmas:stone_quarter_block_horz