give @p const:black_bricks
give @p const:blue_bricks
give @p const:brown_bricks
give @p const:cyan_bricks
give @p const:gray_bricks
give @p const:green_bricks
give @p const:light_blue_bricks
give @p const:light_gray_bricks
give @p const:lime_bricks
give @p const:magenta_bricks
give @p const:orange_bricks
give @p const:pink_bricks
give @p const:purple_bricks
give @p const:red_bricks
give @p const:white_bricks
give @p const:yellow_bricks