give @p const:black_drum
give @p const:blue_drum
give @p const:brown_drum
give @p const:cyan_drum
give @p const:gray_drum
give @p const:green_drum
give @p const:light_blue_drum
give @p const:light_gray_drum
give @p const:lime_drum
give @p const:magenta_drum
give @p const:orange_drum
give @p const:pink_drum
give @p const:purple_drum
give @p const:red_drum
give @p const:white_drum
give @p const:yellow_drum