give @p const:black_plank_button
give @p const:blue_plank_button
give @p const:brown_plank_button
give @p const:cyan_plank_button
give @p const:gray_plank_button
give @p const:green_plank_button
give @p const:light_blue_plank_button
give @p const:light_gray_plank_button
give @p const:lime_plank_button
give @p const:magenta_plank_button
give @p const:orange_plank_button
give @p const:pink_plank_button
give @p const:purple_plank_button
give @p const:red_plank_button
give @p const:white_plank_button
give @p const:yellow_plank_button