give @p const:terracotta_shingles
give @p const:black_terracotta_shingles
give @p const:blue_terracotta_shingles
give @p const:brown_terracotta_shingles
give @p const:cyan_terracotta_shingles
give @p const:gray_terracotta_shingles
give @p const:green_terracotta_shingles
give @p const:light_blue_terracotta_shingles
give @p const:light_gray_terracotta_shingles
give @p const:lime_terracotta_shingles
give @p const:magenta_terracotta_shingles
give @p const:orange_terracotta_shingles
give @p const:pink_terracotta_shingles
give @p const:purple_terracotta_shingles
give @p const:red_terracotta_shingles
give @p const:white_terracotta_shingles
give @p const:yellow_terracotta_shingles