# Diffrent wood types
give @p const:bookshelf_acacia
give @p const:bookshelf_birch
give @p const:bookshelf_dark_oak
give @p const:bookshelf_jungle
give @p const:bookshelf_spruce
give @p const:bookshelf_crimson
give @p const:bookshelf_warped
# all colors
give @p const:black_bookshelf
give @p const:blue_bookshelf
give @p const:brown_bookshelf
give @p const:cyan_bookshelf
give @p const:gray_bookshelf
give @p const:green_bookshelf
give @p const:light_blue_bookshelf
give @p const:light_gray_bookshelf
give @p const:lime_bookshelf
give @p const:magenta_bookshelf
give @p const:orange_bookshelf
give @p const:pink_bookshelf
give @p const:purple_bookshelf
give @p const:red_bookshelf
give @p const:white_bookshelf
give @p const:yellow_bookshelf