give @p const:black_crafting_table
give @p const:blue_crafting_table
give @p const:brown_crafting_table
give @p const:cyan_crafting_table
give @p const:gray_crafting_table
give @p const:green_crafting_table
give @p const:light_blue_crafting_table
give @p const:light_gray_crafting_table
give @p const:lime_crafting_table
give @p const:magenta_crafting_table
give @p const:orange_crafting_table
give @p const:pink_crafting_table
give @p const:purple_crafting_table
give @p const:red_crafting_table
give @p const:white_crafting_table
give @p const:yellow_crafting_table