give @p const:terracotta_large_bricks
give @p const:black_terracotta_large_bricks
give @p const:blue_terracotta_large_bricks
give @p const:brown_terracotta_large_bricks
give @p const:cyan_terracotta_large_bricks
give @p const:gray_terracotta_large_bricks
give @p const:green_terracotta_large_bricks
give @p const:light_blue_terracotta_large_bricks
give @p const:light_gray_terracotta_large_bricks
give @p const:lime_terracotta_large_bricks
give @p const:magenta_terracotta_large_bricks
give @p const:orange_terracotta_large_bricks
give @p const:pink_terracotta_large_bricks
give @p const:purple_terracotta_large_bricks
give @p const:red_terracotta_large_bricks
give @p const:white_terracotta_large_bricks
give @p const:yellow_terracotta_large_bricks