give @p const:black_brick
give @p const:blue_brick
give @p const:brown_brick
give @p const:cyan_brick
give @p const:gray_brick
give @p const:green_brick
give @p const:light_blue_brick
give @p const:light_gray_brick
give @p const:lime_brick
give @p const:magenta_brick
give @p const:orange_brick
give @p const:pink_brick
give @p const:purple_brick
give @p const:red_brick
give @p const:white_brick
give @p const:yellow_brick