give @s moregold:enchanted_golden_banana
give @s moregold:enchanted_golden_grape
give @s moregold:enchanted_golden_lemon
give @s moregold:enchanted_golden_orange
give @s moregold:enchanted_golden_strawberry
give @s moregold:golden_banana
give @s moregold:golden_grape
give @s moregold:golden_lemon
give @s moregold:golden_orange
give @s moregold:golden_strawberry
give @s moregold:golden_fruit_sapling
give @s moregold:golden_fruit_seeds