give @s morepumpkin:lowercase_a_carved_pumpkin
give @s morepumpkin:lowercase_b_carved_pumpkin
give @s morepumpkin:lowercase_c_carved_pumpkin
give @s morepumpkin:lowercase_d_carved_pumpkin
give @s morepumpkin:lowercase_e_carved_pumpkin
give @s morepumpkin:lowercase_f_carved_pumpkin
give @s morepumpkin:lowercase_g_carved_pumpkin
give @s morepumpkin:lowercase_h_carved_pumpkin
give @s morepumpkin:lowercase_i_carved_pumpkin
give @s morepumpkin:lowercase_j_carved_pumpkin
give @s morepumpkin:lowercase_k_carved_pumpkin
give @s morepumpkin:lowercase_l_carved_pumpkin
give @s morepumpkin:lowercase_m_carved_pumpkin
give @s morepumpkin:lowercase_n_carved_pumpkin
give @s morepumpkin:lowercase_o_carved_pumpkin
give @s morepumpkin:lowercase_p_carved_pumpkin
give @s morepumpkin:lowercase_q_carved_pumpkin
give @s morepumpkin:lowercase_r_carved_pumpkin
give @s morepumpkin:lowercase_s_carved_pumpkin
give @s morepumpkin:lowercase_t_carved_pumpkin
give @s morepumpkin:lowercase_u_carved_pumpkin
give @s morepumpkin:lowercase_v_carved_pumpkin
give @s morepumpkin:lowercase_w_carved_pumpkin
give @s morepumpkin:lowercase_x_carved_pumpkin
give @s morepumpkin:lowercase_y_carved_pumpkin
give @s morepumpkin:lowercase_z_carved_pumpkin