give @s morepumpkin:uppercase_a_jack_o_lantern
give @s morepumpkin:uppercase_b_jack_o_lantern
give @s morepumpkin:uppercase_c_jack_o_lantern
give @s morepumpkin:uppercase_d_jack_o_lantern
give @s morepumpkin:uppercase_e_jack_o_lantern
give @s morepumpkin:uppercase_f_jack_o_lantern
give @s morepumpkin:uppercase_g_jack_o_lantern
give @s morepumpkin:uppercase_h_jack_o_lantern
give @s morepumpkin:uppercase_i_jack_o_lantern
give @s morepumpkin:uppercase_j_jack_o_lantern
give @s morepumpkin:uppercase_k_jack_o_lantern
give @s morepumpkin:uppercase_l_jack_o_lantern
give @s morepumpkin:uppercase_m_jack_o_lantern
give @s morepumpkin:uppercase_n_jack_o_lantern
give @s morepumpkin:uppercase_o_jack_o_lantern
give @s morepumpkin:uppercase_p_jack_o_lantern
give @s morepumpkin:uppercase_q_jack_o_lantern
give @s morepumpkin:uppercase_r_jack_o_lantern
give @s morepumpkin:uppercase_s_jack_o_lantern
give @s morepumpkin:uppercase_t_jack_o_lantern
give @s morepumpkin:uppercase_u_jack_o_lantern
give @s morepumpkin:uppercase_v_jack_o_lantern
give @s morepumpkin:uppercase_w_jack_o_lantern
give @s morepumpkin:uppercase_x_jack_o_lantern
give @s morepumpkin:uppercase_y_jack_o_lantern
give @s morepumpkin:uppercase_z_jack_o_lantern