give @s morepumpkin:lowercase_a_jack_o_lantern
give @s morepumpkin:lowercase_b_jack_o_lantern
give @s morepumpkin:lowercase_c_jack_o_lantern
give @s morepumpkin:lowercase_d_jack_o_lantern
give @s morepumpkin:lowercase_e_jack_o_lantern
give @s morepumpkin:lowercase_f_jack_o_lantern
give @s morepumpkin:lowercase_g_jack_o_lantern
give @s morepumpkin:lowercase_h_jack_o_lantern
give @s morepumpkin:lowercase_i_jack_o_lantern
give @s morepumpkin:lowercase_j_jack_o_lantern
give @s morepumpkin:lowercase_k_jack_o_lantern
give @s morepumpkin:lowercase_l_jack_o_lantern
give @s morepumpkin:lowercase_m_jack_o_lantern
give @s morepumpkin:lowercase_n_jack_o_lantern
give @s morepumpkin:lowercase_o_jack_o_lantern
give @s morepumpkin:lowercase_p_jack_o_lantern
give @s morepumpkin:lowercase_q_jack_o_lantern
give @s morepumpkin:lowercase_r_jack_o_lantern
give @s morepumpkin:lowercase_s_jack_o_lantern
give @s morepumpkin:lowercase_t_jack_o_lantern
give @s morepumpkin:lowercase_u_jack_o_lantern
give @s morepumpkin:lowercase_v_jack_o_lantern
give @s morepumpkin:lowercase_w_jack_o_lantern
give @s morepumpkin:lowercase_x_jack_o_lantern
give @s morepumpkin:lowercase_y_jack_o_lantern
give @s morepumpkin:lowercase_z_jack_o_lantern