give @s morepumpkin:uppercase_a_carved_pumpkin
give @s morepumpkin:uppercase_b_carved_pumpkin
give @s morepumpkin:uppercase_c_carved_pumpkin
give @s morepumpkin:uppercase_d_carved_pumpkin
give @s morepumpkin:uppercase_e_carved_pumpkin
give @s morepumpkin:uppercase_f_carved_pumpkin
give @s morepumpkin:uppercase_g_carved_pumpkin
give @s morepumpkin:uppercase_h_carved_pumpkin
give @s morepumpkin:uppercase_i_carved_pumpkin
give @s morepumpkin:uppercase_j_carved_pumpkin
give @s morepumpkin:uppercase_k_carved_pumpkin
give @s morepumpkin:uppercase_l_carved_pumpkin
give @s morepumpkin:uppercase_m_carved_pumpkin
give @s morepumpkin:uppercase_n_carved_pumpkin
give @s morepumpkin:uppercase_o_carved_pumpkin
give @s morepumpkin:uppercase_p_carved_pumpkin
give @s morepumpkin:uppercase_q_carved_pumpkin
give @s morepumpkin:uppercase_r_carved_pumpkin
give @s morepumpkin:uppercase_s_carved_pumpkin
give @s morepumpkin:uppercase_t_carved_pumpkin
give @s morepumpkin:uppercase_u_carved_pumpkin
give @s morepumpkin:uppercase_v_carved_pumpkin
give @s morepumpkin:uppercase_w_carved_pumpkin
give @s morepumpkin:uppercase_x_carved_pumpkin
give @s morepumpkin:uppercase_y_carved_pumpkin
give @s morepumpkin:uppercase_z_carved_pumpkin