give @p const:celingtile_vertical_slab
give @p const:black_celingtile_vertical_slab
give @p const:blue_celingtile_vertical_slab
give @p const:brown_celingtile_vertical_slab
give @p const:cyan_celingtile_vertical_slab
give @p const:gray_celingtile_vertical_slab
give @p const:green_celingtile_vertical_slab
give @p const:light_blue_celingtile_vertical_slab
give @p const:light_gray_celingtile_vertical_slab
give @p const:lime_celingtile_vertical_slab
give @p const:magenta_celingtile_vertical_slab
give @p const:orange_celingtile_vertical_slab
give @p const:pink_celingtile_vertical_slab
give @p const:purple_celingtile_vertical_slab
give @p const:red_celingtile_vertical_slab
give @p const:white_celingtile_vertical_slab
give @p const:yellow_celingtile_vertical_slab