give @p const:black_brick_stairs
give @p const:blue_brick_stairs
give @p const:brown_brick_stairs
give @p const:cyan_brick_stairs
give @p const:gray_brick_stairs
give @p const:green_brick_stairs
give @p const:light_blue_brick_stairs
give @p const:light_gray_brick_stairs
give @p const:lime_brick_stairs
give @p const:magenta_brick_stairs
give @p const:orange_brick_stairs
give @p const:pink_brick_stairs
give @p const:purple_brick_stairs
give @p const:red_brick_stairs
give @p const:white_brick_stairs
give @p const:yellow_brick_stairs