give @s xmas:acacia_eighth_block
give @s xmas:andesite_eighth_block
give @s xmas:birch_eighth_block
give @s xmas:blackstone_eighth_block
give @s xmas:brick_eighth_block
give @s xmas:cobbled_deepslate_eighth_block
give @s xmas:cobblestone_eighth_block
give @s xmas:crimson_eighth_block
give @s xmas:cut_copper_eighth_block
give @s xmas:cut_red_sandstone_eighth_block
give @s xmas:cut_sandstone_eighth_block
give @s xmas:dark_oak_eighth_block
give @s xmas:dark_prismarine_eighth_block
give @s xmas:deepslate_eighth_block
give @s xmas:deepslate_tile_eighth_block
give @s xmas:diorite_eighth_block
give @s xmas:end_stone_eighth_block
give @s xmas:exposed_cut_copper_eighth_block
give @s xmas:granite_eighth_block
give @s xmas:jungle_eighth_block
give @s xmas:mossy_cobblestone_eighth_block
give @s xmas:mossy_stone_brick_eighth_block
give @s xmas:nether_brick_eighth_block
give @s xmas:oak_eighth_block
give @s xmas:oxidized_cut_copper_eighth_block
give @s xmas:polished_andesite_eighth_block
give @s xmas:polished_blackstone_brick_eighth_block
give @s xmas:polished_blackstone_eighth_block
give @s xmas:polished_deepslate_eighth_block
give @s xmas:polished_diorite_eighth_block
give @s xmas:polished_granite_eighth_block
give @s xmas:prismarine_brick_eighth_block
give @s xmas:prismarine_eighth_block
give @s xmas:purpur_eighth_block
give @s xmas:quartz_eighth_block
give @s xmas:stone_eighth_block