give @s xmas:white_present
give @s xmas:orange_present
give @s xmas:magenta_present
give @s xmas:light_blue_present
give @s xmas:yellow_present
give @s xmas:lime_present
give @s xmas:pink_present
give @s xmas:light_gray_present
give @s xmas:gray_present
give @s xmas:cyan_present
give @s xmas:purple_present
give @s xmas:blue_present
give @s xmas:brown_present
give @s xmas:green_present
give @s xmas:red_present
give @s xmas:black_present