give @s xmas:white_terracotta_eighth_block
give @s xmas:orange_terracotta_eighth_block
give @s xmas:magenta_terracotta_eighth_block
give @s xmas:light_blue_terracotta_eighth_block
give @s xmas:yellow_terracotta_eighth_block
give @s xmas:lime_terracotta_eighth_block
give @s xmas:pink_terracotta_eighth_block
give @s xmas:light_gray_terracotta_eighth_block
give @s xmas:gray_terracotta_eighth_block
give @s xmas:cyan_terracotta_eighth_block
give @s xmas:purple_terracotta_eighth_block
give @s xmas:blue_terracotta_eighth_block
give @s xmas:brown_terracotta_eighth_block
give @s xmas:green_terracotta_eighth_block
give @s xmas:red_terracotta_eighth_block
give @s xmas:black_terracotta_eighth_block
give @s xmas:terracotta_eighth_block