give @s xmas:white_concrete_eighth_block
give @s xmas:orange_concrete_eighth_block
give @s xmas:magenta_concrete_eighth_block
give @s xmas:light_blue_concrete_eighth_block
give @s xmas:yellow_concrete_eighth_block
give @s xmas:lime_concrete_eighth_block
give @s xmas:pink_concrete_eighth_block
give @s xmas:light_gray_concrete_eighth_block
give @s xmas:gray_concrete_eighth_block
give @s xmas:cyan_concrete_eighth_block
give @s xmas:purple_concrete_eighth_block
give @s xmas:blue_concrete_eighth_block
give @s xmas:brown_concrete_eighth_block
give @s xmas:green_concrete_eighth_block
give @s xmas:red_concrete_eighth_block
give @s xmas:black_concrete_eighth_block