give @p more_ss:coarse_dirt_vertical_slab
give @p more_ss:cracked_polished_blackstone_brick_vertical_slab
give @p more_ss:cracked_stone_brick_vertical_slab
give @p more_ss:crimson_nylium_vertical_slab
give @p more_ss:dirt_vertical_slab
give @p more_ss:end_stone_vertical_slab
give @p more_ss:gilded_blackstone_vertical_slab
give @p more_ss:mycelium_vertical_slab
give @p more_ss:netherrack_vertical_slab
give @p more_ss:podzol_vertical_slab
give @p more_ss:quartz_brick_vertical_slab
give @p more_ss:red_sand_vertical_slab
give @p more_ss:sand_vertical_slab
give @p more_ss:snow_vertical_slab
give @p more_ss:soul_sand_vertical_slab
give @p more_ss:soul_soil_vertical_slab
give @p more_ss:warped_nylium_vertical_slab
give @p more_ss:cracked_nether_brick_vertical_slab
give @p more_ss:farmland_vertical_slab
give @p more_ss:grass_path_vertical_slab
give @p more_ss:tnt_vertical_slab
give @p more_ss:glowstone_vertical_slab
give @p more_ss:redstone_lamp_vertical_slab
give @p more_ss:crafting_table_vertical_slab
give @p more_ss:honeycomb_block_vertical_slab
give @p more_ss:clay_block_vertical_slab
give @p more_ss:sea_lantern_vertical_slab
give @p more_ss:nether_wart_block_vertical_slab
give @p more_ss:warped_wart_block_vertical_slab
give @p more_ss:grass_block_vertical_slab
give @p more_ss:gravel_vertical_slab
give @p more_ss:ice_vertical_slab
give @p more_ss:packed_ice_vertical_slab
give @p more_ss:blue_ice_vertical_slab
give @p more_ss:obsidian_vertical_slab
give @p more_ss:crying_obsidian_vertical_slab