give @p more_ss:oak_wood_slab
give @p more_ss:spruce_wood_slab
give @p more_ss:birch_wood_slab
give @p more_ss:dark_oak_wood_slab
give @p more_ss:jungle_wood_slab
give @p more_ss:acacia_wood_slab
give @p more_ss:crimson_hyphae_slab
give @p more_ss:warped_hyphae_slab
give @p more_ss:stripped_oak_wood_slab
give @p more_ss:stripped_spruce_wood_slab
give @p more_ss:stripped_birch_wood_slab
give @p more_ss:stripped_dark_oak_wood_slab
give @p more_ss:stripped_jungle_wood_slab
give @p more_ss:stripped_acacia_wood_slab
give @p more_ss:stripped_crimson_hyphae_slab
give @p more_ss:stripped_warped_hyphae_slab