give @p more_ss:coarse_dirt_slab
give @p more_ss:cracked_polished_blackstone_brick_slab
give @p more_ss:cracked_stone_brick_slab
give @p more_ss:crimson_nylium_slab
give @p more_ss:dirt_slab
give @p more_ss:end_stone_slab
give @p more_ss:gilded_blackstone_slab
give @p more_ss:mycelium_slab
give @p more_ss:netherrack_slab
give @p more_ss:podzol_slab
give @p more_ss:quartz_brick_slab
give @p more_ss:red_sand_slab
give @p more_ss:sand_slab
give @p more_ss:snow_slab
give @p more_ss:soul_sand_slab
give @p more_ss:soul_soil_slab
give @p more_ss:warped_nylium_slab
give @p more_ss:cracked_nether_brick_slab
give @p more_ss:farmland_slab
give @p more_ss:grass_path_slab
give @p more_ss:tnt_slab
give @p more_ss:glowstone_slab
give @p more_ss:redstone_lamp_slab
give @p more_ss:crafting_table_slab
give @p more_ss:honeycomb_block_slab
give @p more_ss:clay_block_slab
give @p more_ss:sea_lantern_slab
give @p more_ss:nether_wart_block_slab
give @p more_ss:warped_wart_block_slab
give @p more_ss:grass_block_slab
give @p more_ss:gravel_slab
give @p more_ss:ice_slab
give @p more_ss:packed_ice_slab
give @p more_ss:blue_ice_slab
give @p more_ss:obsidian_slab
give @p more_ss:crying_obsidian_slab