give @p const:black_plank_fence_gate
give @p const:blue_plank_fence_gate
give @p const:brown_plank_fence_gate
give @p const:cyan_plank_fence_gate
give @p const:gray_plank_fence_gate
give @p const:green_plank_fence_gate
give @p const:light_blue_plank_fence_gate
give @p const:light_gray_plank_fence_gate
give @p const:lime_plank_fence_gate
give @p const:magenta_plank_fence_gate
give @p const:orange_plank_fence_gate
give @p const:pink_plank_fence_gate
give @p const:purple_plank_fence_gate
give @p const:red_plank_fence_gate
give @p const:white_plank_fence_gate
give @p const:yellow_plank_fence_gate