give @p more_ss:glass_slab
give @p more_ss:tinted_glass_slab
give @p more_ss:white_stained_glass_slab
give @p more_ss:orange_stained_glass_slab
give @p more_ss:magenta_stained_glass_slab
give @p more_ss:light_blue_stained_glass_slab
give @p more_ss:yellow_stained_glass_slab
give @p more_ss:lime_stained_glass_slab
give @p more_ss:pink_stained_glass_slab
give @p more_ss:gray_stained_glass_slab
give @p more_ss:light_gray_stained_glass_slab
give @p more_ss:cyan_stained_glass_slab
give @p more_ss:purple_stained_glass_slab
give @p more_ss:blue_stained_glass_slab
give @p more_ss:brown_stained_glass_slab
give @p more_ss:green_stained_glass_slab
give @p more_ss:red_stained_glass_slab
give @p more_ss:black_stained_glass_slab
