give @p more_ss:coarse_dirt_stairs
give @p more_ss:cracked_polished_blackstone_brick_stairs
give @p more_ss:cracked_stone_brick_stairs
give @p more_ss:crimson_nylium_stairs
give @p more_ss:dirt_stairs
give @p more_ss:end_stone_stairs
give @p more_ss:gilded_blackstone_stairs
give @p more_ss:mycelium_stairs
give @p more_ss:netherrack_stairs
give @p more_ss:podzol_stairs
give @p more_ss:quartz_brick_stairs
give @p more_ss:red_sand_stairs
give @p more_ss:sand_stairs
give @p more_ss:snow_stairs
give @p more_ss:soul_sand_stairs
give @p more_ss:soul_soil_stairs
give @p more_ss:warped_nylium_stairs
give @p more_ss:cracked_nether_brick_stairs
give @p more_ss:farmland_stairs
give @p more_ss:grass_path_stairs
give @p more_ss:tnt_stairs
give @p more_ss:glowstone_stairs
give @p more_ss:redstone_lamp_stairs
give @p more_ss:crafting_table_stairs
give @p more_ss:honeycomb_block_stairs
give @p more_ss:clay_block_stairs
give @p more_ss:sea_lantern_stairs
give @p more_ss:nether_wart_block_stairs
give @p more_ss:warped_wart_block_stairs
give @p more_ss:grass_block_stairs
give @p more_ss:gravel_stairs
give @p more_ss:ice_stairs
give @p more_ss:packed_ice_stairs
give @p more_ss:blue_ice_stairs
give @p more_ss:obsidian_stairs
give @p more_ss:crying_obsidian_stairs