# Remove all blocks from the players inventory
clear @a canned:empty_can.tile
clear @a canned:apple_can.tile
clear @a canned:baked_potato_can.tile
clear @a canned:beetroot_can.tile
clear @a canned:beetroot_soup_can.tile
clear @a canned:bread_can.tile
clear @a canned:cake_can.tile
clear @a canned:carrot_can.tile
clear @a canned:chorus_fruit_can.tile
clear @a canned:cooked_chicken_can.tile
clear @a canned:cooked_cod_can.tile
clear @a canned:cooked_mutton_can.tile
clear @a canned:cooked_porkchop_can.tile
clear @a canned:cooked_rabbit_can.tile
clear @a canned:cooked_salmon_can.tile
clear @a canned:cooked_beef_can.tile
clear @a canned:cookie_can.tile
clear @a canned:dried_kelp_can.tile
clear @a canned:enchanted_golden_apple_can.tile
clear @a canned:golden_apple_can.tile
clear @a canned:glow_berries_can.tile
clear @a canned:golden_carrot_can.tile
clear @a canned:honey_can.tile
clear @a canned:melon_can.tile
clear @a canned:mushroom_stew_can.tile
clear @a canned:poisonous_potato_can.tile
clear @a canned:potato_can.tile
clear @a canned:pufferfish_can.tile
clear @a canned:pumpkin_pie_can.tile
clear @a canned:rabbit_stew_can.tile
clear @a canned:rotten_flesh_can.tile
clear @a canned:spider_eye_can.tile
clear @a canned:suspicious_stew_can.tile
clear @a canned:sweet_berries_can.tile
clear @a canned:tropical_fish_can.tile