give @p const:celingtile_stairs
give @p const:black_celingtile_stairs
give @p const:blue_celingtile_stairs
give @p const:brown_celingtile_stairs
give @p const:cyan_celingtile_stairs
give @p const:gray_celingtile_stairs
give @p const:green_celingtile_stairs
give @p const:light_blue_celingtile_stairs
give @p const:light_gray_celingtile_stairs
give @p const:lime_celingtile_stairs
give @p const:magenta_celingtile_stairs
give @p const:orange_celingtile_stairs
give @p const:pink_celingtile_stairs
give @p const:purple_celingtile_stairs
give @p const:red_celingtile_stairs
give @p const:white_celingtile_stairs
give @p const:yellow_celingtile_stairs