give @p const:black_snout_stained_glass
give @p const:blue_snout_stained_glass
give @p const:brown_snout_stained_glass
give @p const:cyan_snout_stained_glass
give @p const:gray_snout_stained_glass
give @p const:green_snout_stained_glass
give @p const:light_blue_snout_stained_glass
give @p const:light_gray_snout_stained_glass
give @p const:lime_snout_stained_glass
give @p const:magenta_snout_stained_glass
give @p const:orange_snout_stained_glass
give @p const:pink_snout_stained_glass
give @p const:purple_snout_stained_glass
give @p const:red_snout_stained_glass
give @p const:white_snout_stained_glass
give @p const:yellow_snout_stained_glass
give @p const:tinted_snout_glass